Future_Nostalgia = ("Future Nostalgia",
"Don't Start Now",
"Cool","Physical",
"Levitating",
"Pretty Please",
"Hallucinate",
"Love Again",
"Break My Heart",
"Good in Bed",
"Boys Will Be Boys",
"Fever")

Radical_Optimism = ("End of an Era",
"Houdini",
"Training Season",
"These Walls",
"Whatcha Doing",
"French Exit",
"Illusion",
"Falling Forever",
"Anything for Love",
"Maria",
"Happy for You")

SOUR = ("Brutal","Traitor",
"Drivers License",
"1 Step Forward, 3 Steps Back",
"Deja Vu",
"Good 4 U",
"Enough For You",
"Happier",
"Jealousy, Jealousy",
"Favorite Crime",
"Hope Ur Ok")

GUTS = ("All-American Bitch",
"Bad Idea Right?", 
"Vampire", 
"Lacy", 
"Ballad Of A Homeschooled Girl",
 "Making The Bed", 
"Logical", 
"Get Him Back!", 
"Love Is Embarrassing", 
"The Grudge", 
"Pretty Isn't Pretty", 
"Teenage Dream")

Teenage_Dream = ("Teenage Dream", 
"Last Friday Night (T.G.I.F.)", 
"California Gurls", 
"Firework", 
"Peacock", 
"Circle the Drain", 
"The One That Got Away", 
"E.T.", 
"Who Am I Living For?", 
"Pearl", 
"Hummingbird Heartbeat", 
"Not Like the Movies")

Prism = ("Roar", 
"Legendary Lovers", 
"Birthday", 
"Walking on Air", 
"Unconditionally", 
"Dark Horse", 
"This Is How We Do", 
"International Smile", 
"Ghost", 
"Love Me", 
"This Moment", 
"Double Rainbow", 
"By theGrace of God")